test.py integration with Slack test
Otus-DevOps-2021-02/scramble85_infra pull request #1
Opened 2021-03-16 16:05 UTC by scramble85

2021-03-17 12:00 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Стоит добавить описание к вашему пуллреквесту, так же я указал на что стоит обратить внимание =)

2021-03-17 12:00 UTC, mrgreyves commented on .github/play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Стоит посмотреть на это выражение =)

2021-03-17 17:00 UTC, scramble85 commented on .github/play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
выражение как и сам файл взят из описания к ДЗ
self.assertEqual(1 + 1, 2, "text error")
это чтобы true
стоит исправить, полагаю?

2021-03-18 07:35 UTC, mrgreyves requested changes
Здравствуйте!) В тестах все еще ошибка.

2021-03-18 07:35 UTC, mrgreyves commented on .github/play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
верно!

2021-03-18 08:40 UTC, scramble85 commented
fixed typo in assertEqual

2021-03-18 08:51 UTC, scramble85 commented
wrong folder was committed at the first time. Now checks are good

2021-03-19 06:09 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Все выполнено корректно, дз принимаю!=)

2021-03-19 06:09 UTC, mrgreyves commented on .github/play-travis/test.py
> +        self.assertEqual(1 + 1, 2)
🤘🤘🤘

2021-03-19 11:15 UTC, merged